name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_translate: ^4.0.4
  flutter_stylized_text:
    git: https://github.com/miriamMartinezUB/flutter_stylized_text.git
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  go_router: ^13.2.0
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - locale/
    - assets/images/